### PR TITLE
These files are external libraries and if we include them, SonarQube …

### PR DESCRIPTION
**Pull request by adriannadiaz**
…will count them towards the metrics. This is not recommended practice.

### CODE REVIEW

**Comment by adriannadiaz** [comment]
We are of course still using them, but from the CDN, instead of the files being copied inside our project. This way SonarQube ignores them.

**Comment by Vynny** [comment]
Ok, so someone downloads the app, shuts down their internet connection. Now the indoor maps don't work at all. 

Simply ignore the files explicitly in sonarqube: https://docs.sonarqube.org/display/SONAR/Narrowing+the+Focus

**Comment by Taimoorrana1** [comment]
Agreed with @Vynny. We need to have this code locally

**Comment by adriannadiaz** [comment]
OK This is Pull Request is not needed. I had not yet figured out how to exclude those files.

**Pull request closed without merging**
