### PR TITLE
Buildings name changed in database, added restore script for database.

### PR DESCRIPTION
**Pull request by adriannadiaz**
The database is a binary file that cannot be merged in git. We should backup the database via a restore script in case something horrible happens. ... 😱

### CODE REVIEW

**Comment by arekmano** [comment]
change will conflict with my PR #24, where I also have a similar sql file

**Comment by arekmano** [comment]
I suggest merging this restore script with development.db.sql file. Also, you can modify the DB and insert the values there as well. The SQL file should be used as a backup when the binary file gets into a merge conflict

**Comment by adriannadiaz** [comment]
LOL do I close this or not? It appears @arekmano  just wrote a comment on this.

**Comment by adriannadiaz** [comment]
@Taimoorrana1  merge plz

**Comment by Taimoorrana1** [comment]
I have already approved. Need someone else to review and merge it. We agreed to 2 reviews for a PR to be merged.

**Comment by adriannadiaz** [comment]
This branch and the PR is obsolete.

**Pull request closed without merging**
